name: develop_deploy

on:
  push:
    branches: [ develop ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        env:
          DOCKER_HOST_DEVELOP: ${{ secrets.DOCKER_HOST_DEVELOP }}
          DOCKER_PORT_DEVELOP: ${{ secrets.DOCKER_PORT_DEVELOP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REACT_APP_GITHUB_CLIENT_ID_DEVELOP: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID_DEVELOP }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build --build-arg REACT_APP_GITHUB_CLIENT_ID=$REACT_APP_GITHUB_CLIENT_ID_DEVELOP -t $DOCKER_HOST_DEVELOP:$DOCKER_PORT_DEVELOP/ohbug/web-app .
          docker push $DOCKER_HOST_DEVELOP:$DOCKER_PORT_DEVELOP/ohbug/web-app
  deploy:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST_DEVELOP }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          port: 22
          script: ${{ secrets.DOCKER_DEPLOY_SCRIPT }}
